# Generated by Django 5.2.1 on 2025-05-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Actividad'), ('p', 'Producto')], max_length=1, verbose_name='Tipo de categoría')),
                ('level', models.CharField(choices=[('P', 'Principal'), ('S', 'Secundario'), ('IM', 'Importado por mi'), ('IO', 'Importado por otros')], max_length=2, verbose_name='Nivel de categoría')),
                ('code_sin', models.CharField(max_length=10, verbose_name='Código SIN')),
                ('description_sin', models.TextField(verbose_name='Descripción SIN ')),
                ('short_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='categories.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'constraints': [models.UniqueConstraint(fields=('father', 'code_sin'), name='unique_category')],
            },
        ),
    ]
