# Generated by Django 5.2.1 on 2025-06-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sin', models.CharField(max_length=10, verbose_name='Código SIN')),
                ('description_sin', models.TextField(verbose_name='Descripción SIN')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
                'constraints': [models.UniqueConstraint(fields=('code_sin',), name='unique_economic_activity')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sin', models.CharField(max_length=15, verbose_name='Código SIN')),
                ('description_sin', models.TextField(verbose_name='Descripción SIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('economic_activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='categories.economicactivity', verbose_name='Actividad economica')),
            ],
        ),
    ]
