# Generated by Django 5.2.1 on 2025-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code_sin',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código SIN'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('economic_activity', 'code_sin'), name='unique_economic_activity_category'),
        ),
    ]
