# Generated by Django 5.2.1 on 2025-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_code_sin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicactivity',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Actividad Primaria'),
        ),
    ]
