# Generated by Django 5.2.1 on 2025-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proveedor de autenticación'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Identificador del proveedor de autenticación'),
        ),
    ]
