# Generated by Django 5.2.1 on 2025-11-24 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_provider_user_auth_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=20)),
                ('full_number', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('otp_signed', models.TextField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'full_number'), name='unique_user_full_number')],
            },
        ),
    ]
