# Generated by Django 5.2.1 on 2025-12-11 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userwhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Código OTP')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Usado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('expired', models.DateTimeField(db_index=True, verbose_name='Expira')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'user_otps',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['email', 'is_used', 'expired'], name='user_otps_email_f49cdb_idx'), models.Index(fields=['code', 'expired'], name='user_otps_code_ae5dac_idx')],
            },
        ),
    ]
