# Generated by Django 5.2.1 on 2025-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sin', models.PositiveSmallIntegerField(verbose_name='Código SIN')),
                ('short_name', models.CharField(max_length=6, verbose_name='Abreviatura de la Unidad de Medida')),
                ('name', models.CharField(max_length=70, verbose_name='Descripción de la Unidad de Medida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'constraints': [models.UniqueConstraint(fields=('code_sin', 'short_name', 'name'), name='unique_measure')],
            },
        ),
    ]
