# Generated by Django 5.1.4 on 2025-01-08 23:39

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='access_token',
            field=models.TextField(max_length=builtins.max),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='refresh_token',
            field=models.TextField(max_length=builtins.max),
        ),
    ]
