# Generated by Django 5.1.4 on 2025-02-17 22:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('foundation_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='warehouses.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorcycleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('physical_condition', models.CharField(choices=[('NA', 'NO ARMADO'), ('SA', 'SEMI ARMADO'), ('CA', 'COMPLETAMENTE ARMADO')], max_length=2)),
                ('transaction_status', models.CharField(choices=[('RE', 'RESERVADA'), ('DI', 'DISPONIBLE'), ('VE', 'VENDIDA')], max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_branches', to='warehouses.branch', verbose_name='Sucursal')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mi_motorcycles', to='motorcycles.motorcycle', verbose_name='Motocicleta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
