# Generated by Django 5.2.1 on 2025-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre marca')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_brand_name')],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre color')),
                ('code_hex', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'constraints': [models.UniqueConstraint(fields=('name', 'code_hex'), name='unique_color')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de país (ej. BOL, BRA, CHI)', max_length=5, unique=True, verbose_name='Código de país')),
                ('name', models.CharField(help_text='Nombre legible del origen (ej. Bolivia, Brasil, China)', max_length=70, verbose_name='Nombre del país')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'constraints': [models.UniqueConstraint(fields=('code', 'name'), name='unique_country')],
            },
        ),
    ]
