# Generated by Django 5.2.1 on 2025-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('stock_transaction', models.BooleanField(choices=[(1, 'Entrada'), (0, 'Salida')], default=True, help_text='Indica si el tipo de stock representa una entrada o una salida', verbose_name='¿Es entrada?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de stock',
                'verbose_name_plural': 'Tipos de stock',
            },
        ),
    ]
