# Generated by Django 5.2.1 on 2025-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprice',
            name='max_margin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional: límite absoluto de ganancia para productos caros como motos', max_digits=6, null=True, verbose_name='Tope máximo de ganancia'),
        ),
    ]
