# Generated by Django 5.2.1 on 2025-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_typeprice_max_margin_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeprice',
            name='max_margin_amount',
        ),
        migrations.AddField(
            model_name='typeprice',
            name='profit_margin_motorcycle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen de ganancia para motocicletas del tipo de precio, Ej: 5.00', max_digits=3, null=True, verbose_name='Margen de ganancia motocicleta'),
        ),
        migrations.AlterField(
            model_name='typeprice',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, help_text='Margen de ganancia para productos del tipo de precio, Ej: 10.00', max_digits=5, verbose_name='Margen de ganancia producto'),
        ),
    ]
