# Generated by Django 5.2.1 on 2025-05-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stocktype'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktype',
            constraint=models.UniqueConstraint(fields=('slug', 'stock_transaction'), name='unique_stock_type'),
        ),
    ]
