# Generated by Django 5.2.1 on 2025-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_typeprice_max_margin_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeprice',
            name='profit_margin_motorcycle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen de ganancia para motocicletas del tipo de precio, Ej: 5.00', max_digits=5, null=True, verbose_name='Margen de ganancia motocicleta'),
        ),
    ]
