# Generated by Django 5.2.1 on 2025-09-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_typeprice_profit_margin_motorcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
