# Generated by Django 5.2.1 on 2025-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_color_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brand',
            name='unique_brand_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='product_type',
            field=models.CharField(choices=[('motorcycle', 'Motocicleta'), ('sparepart', 'Repuesto'), ('both', 'Motocicleta y Repuesto')], default='both', max_length=15, verbose_name='Tipo de producto'),
        ),
    ]
