# Generated by Django 5.2.1 on 2025-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_brand_unique_brand_name_brand_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeprice',
            name='profit_margin_motorcycle',
        ),
        migrations.AddField(
            model_name='typeprice',
            name='product_type',
            field=models.CharField(choices=[('motorcycle', 'Motocicleta'), ('sparepart', 'Repuesto'), ('both', 'Motocicleta y Repuesto')], default='both', max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='product_type',
            field=models.CharField(choices=[('motorcycle', 'Motocicleta'), ('sparepart', 'Repuesto'), ('both', 'Motocicleta y Repuesto')], default='both', max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='typeprice',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, help_text='Margen de ganancia para producto del tipo de precio, Ej: 10.00', max_digits=5, verbose_name='Margen de ganancia'),
        ),
    ]
