# Generated by Django 5.1.4 on 2024-12-20 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Abreviatura')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=70, unique=True, verbose_name='Razon social')),
                ('trade_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre comercial')),
                ('document_code', models.CharField(max_length=30, unique=True, verbose_name='Código de documento')),
                ('document_type', models.ForeignKey(blank=True, help_text='Selecciona el tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_persons', related_query_name='%(class)s_person', to='persons.documenttype', verbose_name='Tipo de documento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company_name', 'document_code'), name='unique_company_document_code')],
            },
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('paternal_surname', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('gender', models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='', max_length=1, verbose_name='Género de la persona')),
                ('document_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Codigo de documento')),
                ('document_complement', models.CharField(blank=True, default='', help_text='Codigo complemento para documentos duplicados', max_length=3, verbose_name='Complemento de documento')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('document_type', models.ForeignKey(blank=True, help_text='Selecciona el tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_persons', related_query_name='%(class)s_person', to='persons.documenttype', verbose_name='Tipo de documento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document_code', 'document_complement'), name='unique_person_document_complement')],
            },
        ),
    ]
