# Generated by Django 5.1.4 on 2025-01-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalperson',
            name='document_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código de identificación'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='document_code',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Codigo de documento'),
        ),
    ]
