# Generated by Django 5.2.1 on 2025-12-03 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency_code', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('REVIEWED', 'Revisado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='CREATED', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['quotation', 'product'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='quotations_status_5ae774_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['user'], name='quotations_user_id_fa08df_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created'], name='quotations_created_4ba242_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['expired'], name='quotations_expired_ba3a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['quotation'], name='quotations__quotati_3cfc02_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['product'], name='quotations__product_b1a2d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.UniqueConstraint(fields=('quotation', 'product'), name='uq_quotation_product'),
        ),
    ]
