# Generated by Django 5.2.1 on 2025-12-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió notificación de expiración', verbose_name='Notificación enviada'),
        ),
    ]
