# Generated by Django 5.1.4 on 2025-02-17 22:21

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycles', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('motorcycle', models.ManyToManyField(blank=True, help_text='Motocicletas del accionista', related_name='sh_motorcycles', related_query_name='sh_motorcycle', to='motorcycles.motorcycle', verbose_name='Motocicletas')),
                ('natural_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder', to='persons.naturalperson', verbose_name='Persona asociada')),
            ],
            options={
                'verbose_name': 'Accionista',
                'verbose_name_plural': 'Accionistas',
            },
        ),
    ]
