# Generated by Django 5.1.4 on 2025-02-17 22:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_type', models.CharField(choices=[('n', 'Persona natural'), ('l', 'Persona jurídica')], default='n', help_text='Selecciona el tipo de persona', max_length=1, verbose_name='Tipo persona')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('legal_person', models.ForeignKey(blank=True, help_text='Selecciona una persona jurídica', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss_legal_perosn', related_query_name='%(class)s_legal_person', to='persons.legalperson', verbose_name='Persona jurídica')),
                ('natural_person', models.ForeignKey(blank=True, help_text='Selecciona una persona natural', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss_natural_perosn', related_query_name='%(class)s_natural_person', to='persons.naturalperson', verbose_name='Persona natural')),
            ],
        ),
    ]
