# Generated by Django 5.2.1 on 2025-05-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tipo de precio, Ej: Precio de venta, Precio de compra', max_length=50, verbose_name='Nombre del tipo de precio')),
                ('slug', models.SlugField(help_text='Slug del tipo de precio, Ej: precio-venta, precio-compra', unique=True, verbose_name='Slug del tipo de precio')),
                ('profit_margin', models.DecimalField(decimal_places=2, help_text='Margen de ganancia del tipo de precio, Ej: 10.00', max_digits=5, verbose_name='Margen de ganancia')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el tipo de precio está activo o no', verbose_name='Tipo de precio activo')),
            ],
            options={
                'verbose_name': 'Tipo de precio',
                'verbose_name_plural': 'Tipos de precios',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la moneda, Ej: Dólar, Boliviano, Euro', max_length=50, verbose_name='Nombre de la moneda')),
                ('code', models.CharField(help_text='Código de la moneda, Ej: USD, BOB', max_length=3, unique=True, verbose_name='Código de la moneda')),
                ('symbol', models.CharField(help_text='Símbolo de la moneda, Ej: $, Bs, €', max_length=5, verbose_name='Símbolo de la moneda')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la moneda está activa o no', verbose_name='Moneda activa')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'constraints': [models.UniqueConstraint(fields=('name', 'code', 'symbol'), name='unique_currency')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Tasa de cambio')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización de la tasa de cambio', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la tasa de cambio está activa o no', verbose_name='Tasa de cambio activa')),
                ('from_currency', models.ForeignKey(help_text='Moneda de origen, Ej: USD', on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', related_query_name='from_rate', to='prices.currency', verbose_name='Moneda de origen')),
                ('to_currency', models.ForeignKey(help_text='Moneda de destino, Ej: BOB', on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', related_query_name='to_rate', to='prices.currency', verbose_name='Moneda de destino')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasa de cambio',
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency'), name='unique_exchange_rate'), models.CheckConstraint(condition=models.Q(('from_currency', models.F('to_currency')), _negated=True), name='no_same_currency')],
            },
        ),
    ]
