# Generated by Django 5.2.1 on 2025-06-26 13:15

import apps.motorcycles.functions.motorcycle_photo
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug de la clase de la motocicleta')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Clase de motocicleta')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clase motocicleta',
                'verbose_name_plural': 'Clases de motocicleta',
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Tipo transmisión')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tipo motocicleta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('is_subtype', models.BooleanField(default=False, help_text='Indica si este es un subtipo de otro tipo de motocicleta', verbose_name='Es subtipo')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtype', to='motorcycles.motorcycletype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo motocicleta',
                'verbose_name_plural': 'Tipos de motocicletas',
            },
        ),
        migrations.CreateModel(
            name='MotorcyclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('base', models.DecimalField(decimal_places=2, help_text='Precio base del tipo de motocicleta', max_digits=12, verbose_name='Precio base')),
                ('brand', models.ForeignKey(help_text='Marca de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_prices', related_query_name='motorcycle_price', to='core.brand', verbose_name='Marca')),
                ('currency', models.ForeignKey(help_text='Moneda del precio para el tipo de motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_prices', related_query_name='motorcycle_price', to='core.currency', verbose_name='Moneda')),
                ('motorcycle_type', models.ForeignKey(help_text='Tipo de motocicleta al que pertenece el precio', on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_prices', related_query_name='motorcycle_price', to='motorcycles.motorcycletype', verbose_name='Tipo de motocicleta')),
            ],
            options={
                'verbose_name': 'Precio de motocicleta',
                'verbose_name_plural': 'Precio de motocicletas',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(help_text='Marca de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='pm_brands', related_query_name='pm_brand', to='core.brand', verbose_name='Marca')),
                ('color', models.ForeignKey(help_text='Color del tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='pm_colors', related_query_name='pm_color', to='core.color', verbose_name='Color')),
                ('motorcycle_type', models.ForeignKey(help_text='Tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='pm_motorcycle_types', related_query_name='pm_motorcycle_type', to='motorcycles.motorcycletype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Archivo de motocicleta',
                'verbose_name_plural': 'Archivos de motocicleta',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_dim', models.CharField(max_length=70, unique=True, verbose_name='Código DIM')),
                ('code_fvr', models.CharField(max_length=70, unique=True, verbose_name='Código FVR')),
                ('model_year', models.PositiveIntegerField(verbose_name='Año modelo')),
                ('manufacturing_year', models.PositiveIntegerField(verbose_name='Año fabricación')),
                ('code_chasis', models.CharField(max_length=50, unique=True, verbose_name='Código chasis')),
                ('code_motor', models.CharField(max_length=50, unique=True, verbose_name='Código motor')),
                ('number_cc', models.PositiveSmallIntegerField(verbose_name='Número cilindrada')),
                ('declaration_code', models.CharField(blank=True, help_text='Ingrese el código de declaración (opcional)', max_length=120, null=True, verbose_name='Código de declaración')),
                ('brand', models.ForeignKey(help_text='Marca de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_brands', related_query_name='m_brand', to='core.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(help_text='Categoría de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_categories', related_query_name='m_category', to='categories.category', verbose_name='Categoría')),
                ('color', models.ForeignKey(help_text='Color de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_colors', related_query_name='m_color', to='core.color', verbose_name='Color')),
                ('country', models.ForeignKey(help_text='Origen de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_countries', related_query_name='m_country', to='core.country', verbose_name='Origen')),
                ('motorcycle_class', models.ForeignKey(help_text='Clase de motocicleta al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='m_motorcycle_classes', related_query_name='m_motorcycle_class', to='motorcycles.motorcycleclass', verbose_name='Clase de motocicleta')),
                ('motorcycle_type', models.ForeignKey(help_text='Tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_pmotorcycle_types', related_query_name='m_motorcycle_type', to='motorcycles.motorcycletype', verbose_name='Tipo y subtipo')),
                ('transmission_type', models.ForeignKey(help_text='Tipo y sub tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_transmission_types', related_query_name='m_transmission_type', to='motorcycles.transmissiontype', verbose_name='Tipo de transmisión')),
            ],
            options={
                'verbose_name': 'Motocicleta',
                'verbose_name_plural': 'Motocicletas',
            },
        ),
        migrations.CreateModel(
            name='MotorcyclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('photo', models.ImageField(upload_to=apps.motorcycles.functions.motorcycle_photo.upload_to_s3, verbose_name='Foto')),
                ('motorcycle_file', models.ForeignKey(help_text='Archivo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='p_motorcycle_files', related_query_name='p_motorcycle_file', to='motorcycles.motorcyclefile', verbose_name='Motocicleta')),
            ],
            options={
                'verbose_name': 'Foto de motocicleta',
                'verbose_name_plural': 'Fotos de motocicleta',
                'indexes': [models.Index(fields=['created'], name='motorcycles_created_519875_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='motorcycletype',
            constraint=models.UniqueConstraint(fields=('name', 'father'), name='unique_motorcycle_type'),
        ),
        migrations.AddConstraint(
            model_name='motorcycleprice',
            constraint=models.UniqueConstraint(fields=('motorcycle_type', 'brand', 'currency'), name='unique_motorcycle_price'),
        ),
        migrations.AddConstraint(
            model_name='motorcyclefile',
            constraint=models.UniqueConstraint(fields=('motorcycle_type', 'color', 'brand'), name='unique_motorcycle_photo'),
        ),
        migrations.AddConstraint(
            model_name='motorcycle',
            constraint=models.UniqueConstraint(fields=('code_dim', 'code_chasis', 'code_motor', 'code_fvr'), name='unique_motorcycle'),
        ),
    ]
