# Generated by Django 5.1.4 on 2025-02-17 22:17

import apps.motorcycles.functions
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(help_text='Código ISO 4217 de la moneda (USD, EUR, CLP, etc.)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('conversion_rate', models.DecimalField(decimal_places=4, help_text='Tasa de cambio respecto a la moneda base', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Tipo transmisión')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre marca')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_brand')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='motorcycles.category', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre color')),
                ('code_hex', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'constraints': [models.UniqueConstraint(fields=('name', 'code_hex'), name='unique_color')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del país')),
                ('short_name', models.CharField(max_length=10, null=True, unique=True, verbose_name='Abreviado del país')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'constraints': [models.UniqueConstraint(fields=('name', 'short_name'), name='unique_country')],
            },
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('n', 'Persona natural'), ('l', 'Persona jurídica')], default='n', help_text='Selecciona el tipo de persona', max_length=1, verbose_name='Tipo persona')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('legal_person', models.ForeignKey(blank=True, help_text='Selecciona una persona jurídica', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss_legal_perosn', related_query_name='%(class)s_legal_person', to='persons.legalperson', verbose_name='Persona jurídica')),
                ('natural_person', models.ForeignKey(blank=True, help_text='Selecciona una persona natural', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss_natural_perosn', related_query_name='%(class)s_natural_person', to='persons.naturalperson', verbose_name='Persona natural')),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tipo motocicleta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtype', to='motorcycles.motorcycletype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo motocicleta',
                'verbose_name_plural': 'Tipos de motocicletas',
            },
        ),
        migrations.CreateModel(
            name='MotorcyclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('orientation', models.CharField(choices=[('V', 'Vertical'), ('H', 'Horizontal')], max_length=1, verbose_name='Orientación de la foto')),
                ('side_direction', models.CharField(choices=[('P', 'Portada'), ('F', 'Frontal'), ('T', 'Trasera'), ('I', 'Izquierda'), ('D', 'Derecha')], max_length=1, verbose_name='Dirección de lado')),
                ('image_url', models.ImageField(upload_to=apps.motorcycles.functions.get_image_path, verbose_name='Foto')),
                ('color', models.ForeignKey(help_text='Color del tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='pm_colors', related_query_name='pm_color', to='motorcycles.color', verbose_name='Color')),
                ('motorcycle_type', models.ForeignKey(help_text='Tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='pm_motorcycle_types', related_query_name='pm_motorcycle_type', to='motorcycles.motorcycletype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_dim', models.CharField(max_length=70, unique=True, verbose_name='Código DIM')),
                ('code_fvr', models.CharField(max_length=70, unique=True, verbose_name='Código FVR')),
                ('model_year', models.PositiveIntegerField(verbose_name='Año modelo')),
                ('manufacturing_year', models.PositiveIntegerField(verbose_name='Año fabricación')),
                ('code_chasis', models.CharField(max_length=50, unique=True, verbose_name='Código chasis')),
                ('code_motor', models.CharField(max_length=50, unique=True, verbose_name='Código motor')),
                ('number_cc', models.PositiveSmallIntegerField(verbose_name='Número cilindrada')),
                ('declaration_code', models.CharField(blank=True, help_text='Ingrese el código de declaración de QR', max_length=70, null=True, verbose_name='Declaración code')),
                ('brand', models.ForeignKey(help_text='Marca de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_brands', related_query_name='m_brand', to='motorcycles.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(help_text='Categoría de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_categories', related_query_name='m_category', to='motorcycles.category', verbose_name='Categoría')),
                ('color', models.ForeignKey(help_text='Color de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_colors', related_query_name='m_color', to='motorcycles.color', verbose_name='Color')),
                ('country', models.ForeignKey(help_text='Origen de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_countries', related_query_name='m_country', to='motorcycles.country', verbose_name='Origen')),
                ('importer', models.ForeignKey(help_text='Importador de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_importers', related_query_name='m_importer', to='motorcycles.importer', verbose_name='Importador')),
                ('motorcycle_type', models.ForeignKey(help_text='Tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_pmotorcycle_types', related_query_name='m_motorcycle_type', to='motorcycles.motorcycletype', verbose_name='Tipo y subtipo')),
                ('transmission_type', models.ForeignKey(help_text='Tipo y sub tipo de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='m_transmission_types', related_query_name='m_transmission_type', to='motorcycles.transmissiontype', verbose_name='Tipo de transmisión')),
            ],
            options={
                'verbose_name': 'Motocicleta',
                'verbose_name_plural': 'Motocicletas',
            },
        ),
        migrations.CreateModel(
            name='MotorcyclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.99)])),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descripción')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_currencies', related_query_name='mp_currency', to='motorcycles.currency', verbose_name='Motocicleta')),
                ('motorcycle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_motorcycle_types', related_query_name='mp_motorcycle_type', to='motorcycles.motorcycletype', verbose_name='Tipo motocicleta')),
                ('type_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_type_prices', related_query_name='mp_type_price', to='motorcycles.typeprice', verbose_name='Tipo precio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category'),
        ),
        migrations.AddConstraint(
            model_name='motorcycletype',
            constraint=models.UniqueConstraint(fields=('name', 'father'), name='unique_motorcycle_type'),
        ),
        migrations.AddConstraint(
            model_name='motorcycle',
            constraint=models.UniqueConstraint(fields=('code_dim', 'code_chasis', 'code_motor', 'code_fvr'), name='unique_motorcycle'),
        ),
    ]
