# Generated by Django 5.2.1 on 2025-09-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmissiontype',
            options={'verbose_name': 'Tipo transmisión', 'verbose_name_plural': 'Tipos de transmisión'},
        ),
    ]
