# Generated by Django 5.2.1 on 2025-05-20 13:10

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('motorcycles', '0001_initial'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcyclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('base', models.DecimalField(decimal_places=2, help_text='Precio base del tipo de motocicleta', max_digits=12, verbose_name='Precio base')),
                ('brand', models.ForeignKey(help_text='Marca de la motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_prices', related_query_name='motorcycle_price', to='core.brand', verbose_name='Marca')),
                ('currency', models.ForeignKey(help_text='Moneda del precio para el tipo de motocicleta', on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_prices', related_query_name='motorcycle_price', to='prices.currency', verbose_name='Moneda')),
                ('motorcycle_type', models.ForeignKey(help_text='Tipo de motocicleta al que pertenece el precio', on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_prices', related_query_name='motorcycle_price', to='motorcycles.motorcycletype', verbose_name='Tipo de motocicleta')),
            ],
            options={
                'verbose_name': 'Precio de motocicleta',
                'verbose_name_plural': 'Precio de motocicletas',
                'constraints': [models.UniqueConstraint(fields=('motorcycle_type', 'brand', 'currency'), name='unique_motorcycle_price')],
            },
        ),
    ]
