# Generated by Django 5.1.4 on 2025-02-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='modified',
        ),
    ]
