# Generated by Django 5.2.1 on 2025-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_alter_transmissiontype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcyclefile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el archivo está activo', verbose_name='Activo'),
        ),
    ]
