# Generated by Django 5.1.4 on 2025-02-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_remove_brand_created_remove_brand_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorcyclephoto',
            options={'verbose_name': 'Foto de motocicleta', 'verbose_name_plural': 'Fotos de motocicletas'},
        ),
        migrations.AddConstraint(
            model_name='motorcyclephoto',
            constraint=models.UniqueConstraint(fields=('motorcycle_type', 'color', 'side_direction'), name='unique_side_by_motorcycle_type_and_color'),
        ),
        migrations.AddConstraint(
            model_name='motorcyclephoto',
            constraint=models.UniqueConstraint(condition=models.Q(('side_direction', 'P')), fields=('motorcycle_type', 'color', 'orientation'), name='unique_cover_by_orientation'),
        ),
    ]
