# Generated by Django 5.1.4 on 2025-02-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0003_alter_motorcyclephoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='motorcyclephoto',
            name='unique_side_by_motorcycle_type_and_color',
        ),
        migrations.RemoveConstraint(
            model_name='motorcyclephoto',
            name='unique_cover_by_orientation',
        ),
        migrations.AddConstraint(
            model_name='motorcyclephoto',
            constraint=models.UniqueConstraint(fields=('motorcycle_type', 'color', 'side_direction'), name='unique_motorcycle_photo_by_type_color_side'),
        ),
    ]
