# Generated by Django 5.1.4 on 2025-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0004_remove_motorcyclephoto_unique_side_by_motorcycle_type_and_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='motorcyclephoto',
            name='unique_motorcycle_photo_by_type_color_side',
        ),
        migrations.AddConstraint(
            model_name='motorcyclephoto',
            constraint=models.UniqueConstraint(condition=models.Q(('side_direction', 'portada'), _negated=True), fields=('motorcycle_type', 'color', 'side_direction'), name='unique_motorcycle_photo_by_type_color_side'),
        ),
    ]
