# Generated by Django 5.1.4 on 2025-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0006_remove_motorcyclephoto_unique_motorcycle_photo_by_type_color_side_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='motorcyclephoto',
            constraint=models.UniqueConstraint(condition=models.Q(('side_direction', 'P')), fields=('motorcycle_type', 'color', 'orientation'), name='unique_cover_by_orientation'),
        ),
    ]
