# Generated by Django 5.1.4 on 2025-02-17 22:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '__first__'),
        ('warehouses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.99)])),
                ('motorcycle_inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pn_motorcycle_inventory', to='warehouses.motorcycleinventory')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pn_purchase', to='purchases.purchase')),
            ],
        ),
    ]
