# Generated by Django 5.2.1 on 2025-06-26 13:15

import apps.products.functions.product_photo
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código del producto', max_length=30, unique=True, verbose_name='Código del producto')),
                ('description', models.TextField(help_text='Descripción del producto', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Estado del producto', verbose_name='Estado')),
                ('brand', models.ForeignKey(blank=True, help_text='Marca del producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_brands', related_query_name='p_brand', to='core.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.CASCADE, related_name='p_categories', related_query_name='p_category', to='categories.category', verbose_name='Categoría')),
                ('country', models.ForeignKey(blank=True, help_text='Industria del producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_countries', related_query_name='p_countrie', to='core.country', verbose_name='Industria')),
                ('measure', models.ForeignKey(help_text='Unidad medida del producto', on_delete=django.db.models.deletion.CASCADE, related_name='p_measures', related_query_name='p_measure', to='measures.measure', verbose_name='Unidad medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('photo', models.ImageField(help_text='Nombre de la foto del producto', upload_to=apps.products.functions.product_photo.upload_to_s3, verbose_name='Foto')),
                ('product', models.ForeignKey(help_text='Producto al que pertenece la foto', on_delete=django.db.models.deletion.CASCADE, related_name='p_photos', related_query_name='p_photo', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de producto',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('base', models.DecimalField(decimal_places=2, help_text='Precio base del producto', max_digits=12, verbose_name='Precio base')),
                ('currency', models.ForeignKey(help_text='Moneda del precio del producto', on_delete=django.db.models.deletion.CASCADE, related_name='p_prices', related_query_name='p_price', to='core.currency', verbose_name='Moneda')),
                ('product', models.ForeignKey(help_text='Producto al que pertenece el precio', on_delete=django.db.models.deletion.CASCADE, related_name='p_prices', related_query_name='p_price', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Precio de producto',
                'verbose_name_plural': 'Precios de producto',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos para este tipo de movimiento', verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='core.stocktype')),
            ],
            options={
                'verbose_name': 'Stock de producto',
                'verbose_name_plural': 'Stocks de producto',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='products_pr_created_9a1943_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'code'), name='unique_product'),
        ),
        migrations.AddIndex(
            model_name='productphoto',
            index=models.Index(fields=['created'], name='products_pr_created_0fc8e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'currency'), name='unique_product_price'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'stock_type'), name='unique_product_stock'),
        ),
    ]
