# Generated by Django 5.2.1 on 2025-05-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Precio de producto', 'verbose_name_plural': 'Precio del productos'},
        ),
    ]
