# Generated by Django 5.2.1 on 2025-05-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stocktype'),
        ('products', '0002_alter_productprice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos para este tipo de movimiento', verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='core.stocktype')),
            ],
            options={
                'verbose_name': 'Movimiento producto stock',
                'verbose_name_plural': 'Movimientos producto stock',
            },
        ),
    ]
