# Generated by Django 5.2.1 on 2025-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stocktype'),
        ('products', '0003_productstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Foto de producto', 'verbose_name_plural': 'Fotos de producto'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Precio de producto', 'verbose_name_plural': 'Precios de producto'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Stock de producto', 'verbose_name_plural': 'Stocks de producto'},
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'stock_type'), name='unique_product_stock'),
        ),
    ]
